chore: husky 설정

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -13,8 +13,8 @@ echo "$formatted_files" | xargs ./node_modules/.bin/prettier --write --check || 
 echo "Prettier 완료"
 
 # ESLint로 선택된 파일을 검사하세요. 오류가 있으면 알려주고 실패한 경우 목록을 출력합니다.
-echo "$files_to_lint" | xargs ./node_modules/.bin/eslint || (echo "Linting check failed. See the errors above" && exit 1)
-
+# echo "$files_to_lint" | xargs ./node_modules/.bin/eslint || (echo "Linting check failed. See the errors above" && exit 1)
+echo "$files_to_lint" | xargs ./node_modules/.bin/eslint --quiet
 echo "Lint 완료"
 
 # 모든 변경 내용을 다시 추가합니다.
